version: '3.7'

services:

    clickhouse:

        image: yandex/clickhouse-server:20.6.6.7
        ports:
          - 8123:8123
          - 9000:9000
        volumes:
          - ./parquet_files:/opt/parquet_files
          - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        container_name: some-clickhouse-server